apiVersion: apps/v1

kind: Deployment

metadata:
  name: deployment1


spec:
  replicas: 3

  selector:
    matchLabels:
      label-name: "t1"

  template:
    metadata:
        name: pod1
        labels:
          label-name: "t1"

    spec:
        containers:
        - name: container1
          image: alihaamed17/os2-task:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"

